### ISSUE TITLE
Add sorting UI and logic to sort favorite movies by date

### ISSUE THREAD

**Issue by tatemz** [zhangdshr/FavMoviesKotlin#1]
This is a feature request to implement a sorting mechanism to the Favorite Movies screen in order to sort the list of movies by release date.

The UI should be clean and user-friendly and allow for the sorting by date to be ascending or descending.

To be completed by Jan 16th, 2020

**Comment by tatemz** [comment]
Make a PR to close out this issue.

**Comment by zhangdshrft** [comment]
I have update the code include this new feature, it use MutableList sortBy and sortedByDescending methods to implement sort data by date(Year).

**Comment by zhangdshr** [comment]
fun sortByDataAscending() {
        items.sortBy { it.Year }
    }

    fun sortByDataDescending() {
        items.sortedByDescending { it.Year }
    }

**Comment by zhangdshrft** [comment]
This is the key of the code

fun sortByDataAscending() {
        items.sortBy { it.Year }
}
fun sortByDataDescending() {
        items.sortedByDescending { it.Year }
}
